apiVersion: v1
kind: Pod
metadata:
  name: cons-pod
  labels:
    app: fun-facts
    role: consumer
spec:
  containers:
  - name: cons-container
    image: shekeriev/k8s-consumer:latest
    ports:
    - containerPort: 5000