apiVersion: v1
kind: Pod
metadata:
  name: prod-pod
  labels:
    app: fun-facts
    role: producer
spec:
  containers:
  - name: prod-container
    image: shekeriev/k8s-producer:latest
    ports:
    - containerPort: 5000