apiVersion: v1
kind: Service
metadata:
  name: consumer
  labels:
    app: fun-facts
    role: consumer
spec:
  type: LoadBalancer
  ports:
  - port: 5000
    protocol: TCP
  selector:
    app: fun-facts
    role: consumer