apiVersion: v1
kind: Service
metadata:
  name: appx-svc
  labels:
    app: appx
    ver: v1
spec:
  type: NodePort
  ports:
  - port: <<service-port>>
    targetPort: <<pod-port>>
    nodePort: <<external-port>>
    protocol: TCP
  selector:
    app: <<svc-app>>
    ver: <<svc-ver>>
